apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default   # optional if you are using default namespace
spec:
  selector:
    app: vprofile-app
  ports:
    - protocol: TCP
      port: 8080        # Service port
      targetPort: 8080  # Container port
  type: ClusterIP       # Default type

