apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
data:
  01-init.sql: |
    CREATE DATABASE IF NOT EXISTS accounts;
    GRANT ALL PRIVILEGES ON accounts.* TO 'admin'@'%' IDENTIFIED BY 'admin123';
    GRANT ALL PRIVILEGES ON accounts.* TO 'admin'@'localhost' IDENTIFIED BY 'admin123';
    FLUSH PRIVILEGES;

    USE accounts;
    DROP TABLE IF EXISTS `role`;
    CREATE TABLE `role` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(45) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

    LOCK TABLES `role` WRITE;
    INSERT INTO `role` VALUES (1,'ROLE_USER');
    UNLOCK TABLES;

    DROP TABLE IF EXISTS `user`;
    CREATE TABLE `user` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `username` varchar(255) DEFAULT NULL,
      `userEmail` varchar(255) DEFAULT NULL,
      `profileImg` varchar(255) DEFAULT NULL,
      `profileImgPath` varchar(255) DEFAULT NULL,
      `dateOfBirth` varchar(255) DEFAULT NULL,
      `fatherName` varchar(255) DEFAULT NULL,
      `motherName` varchar(255) DEFAULT NULL,
      `gender` varchar(255) DEFAULT NULL,
      `maritalStatus` varchar(255) DEFAULT NULL,
      `permanentAddress` varchar(255) DEFAULT NULL,
      `tempAddress` varchar(255) DEFAULT NULL,
      `primaryOccupation` varchar(255) DEFAULT NULL,
      `secondaryOccupation` varchar(255) DEFAULT NULL,
      `skills` varchar(255) DEFAULT NULL,
      `phoneNumber` varchar(255) DEFAULT NULL,
      `secondaryPhoneNumber` varchar(255) DEFAULT NULL,
      `nationality` varchar(255) DEFAULT NULL,
      `language` varchar(255) DEFAULT NULL,
      `workingExperience` varchar(255) DEFAULT NULL,
      `password` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;
    LOCK TABLES `user` WRITE;
    INSERT INTO `user` VALUES 
    (7,'admin_vp','admin@hkhinfo.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$11$0a7VdTr4rfCQqtsvpng6GuJnzUmQ7gZiHXgzGPgm5hkRa3avXgBLK');
    UNLOCK TABLES;

    DROP TABLE IF EXISTS `user_role`;
    CREATE TABLE `user_role` (
      `user_id` int(11) NOT NULL,
      `role_id` int(11) NOT NULL,
      PRIMARY KEY (`user_id`,`role_id`),
      KEY `fk_user_role_roleid_idx` (`role_id`),
      CONSTRAINT `fk_user_role_roleid` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
      CONSTRAINT `fk_user_role_userid` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

