apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mariadb-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mariadb-data   # المجلد اللي هيخزن البيانات على النود
    type: DirectoryOrCreate

