apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306       # Port inside the cluster
      targetPort: 3306 # Port the container listens on
  type: ClusterIP     # Internal access only

