apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  # كلمات المرور مشفرة بـ base64
  mysql-root-password: cm9vdDEyMw==       # root123
  mysql-user: YWRtaW4=                     # admin
  mysql-password: YWRtaW4xMjM=             # admin123

